### ISSUE TITLE
How to handle Exit logging?

### ISSUE THREAD

**Issue by ecerroni** [Logflare/pino-logflare#11]
When my Node process crashes I am losing the logs from the stream implementation.

Indeed the official pino documentation states using streams might be problematic: https://github.com/pinojs/pino/blob/master/docs/help.md#exit-logging

What should I do to be able to send logs to logflare also when node has crashed? Thanks.

**UPDATE**: I was able to achieve the desired result implementing a workaround that uses an old npm package. This is the code in the server:
```
const exitHandler = terminate(httpServer, {
  coredump: false,
  timeout: 500,
})
process.on('uncaughtException', exitHandler(1, 'Unexpected Error'))
process.on('unhandledRejection', exitHandler(1, 'Unhandled Promise'))
process.on('SIGTERM', exitHandler(0, 'SIGTERM'))
process.on('SIGINT', exitHandler(0, 'SIGINT'))
```

This is the terminate javascript file:
```
import { logflare } from '~/config';
import { isProduction } from '~/environment'
import * as wait from 'wait.for'


const terminate = (server, options = { coredump: false, timeout: 500 }) => {
  // Exit function
  const exit = code => {
    if (options.coredump) {
      process.abort()
    } else process.exit(code)
  }

  const log = (code, reason, err) => {
    if (err && err instanceof Error) {
      wait.forMethod(logflare, 'error', { reason, code: err.code || code, message: err.message, stack: err.stack }, '[ERROR][ROOT]')
    } else wait.forMethod(logflare, 'fatal', {
      code: err.code || code,
      reason,
      message: err.message,
      stack: err.stack
    }, '[FATAL][ROOT]')
    
  
    server.close(exit)
    setTimeout(exit, options.timeout).unref()
  }

  return (code, reason) => (err, promise) => {
    wait.launchFiber(log, code, reason, err);
  }
}

export default terminate

```

Feel free to reopen this issue if you plan to address this kind of situations natively in pino-logflare

**Comment by chasers** [comment]
Hey thanks! Sorry for the delayed response. Just forgot to get back to this. I actually had it on my list to figure that all out. Would love to handle this in the lib. Open to suggestions.
