### ISSUE TITLE
No logs appear on Logflare

### ISSUE THREAD

**Issue by ErnestBrandi** [Logflare/pino-logflare#16]
Hi, **EDIT** just found it was because I was using 
```
prettyPrint: {
    levelFirst: true,
},
```
in `pino` options.

**Comment by chasers** [comment]
So this works for you now? But it does not work with `pino-pretty`? I haven't tested `pino-pretty` with `pino-logflare`.

**Comment by ErnestBrandi** [comment]
Yes, using `pino-pretty` cause the logs to not print anything.
Also, I have tried the VERCEL example (https://github.com/Logflare/pino-logflare/blob/master/docs/VERCEL.md), without `pino-pretty` of course, and it does not work either.
Using the regular example (https://github.com/Logflare/pino-logflare/blob/master/docs/API.md), does work though.

**Comment by chasers** [comment]
Marking this as #wontfix since the Logflare UI pretty prints the JSON logs for you.
