### ISSUE TITLE
stream_1.default.Writable is not a constructor

### ISSUE THREAD

**Issue by chasers** [Logflare/pino-logflare#20]
TypeError: stream_1.default.Writable is not a constructor
const { send, stream } = logflarePinoVercel({ apiKey, sourceToken })
using in next.js app
"dependencies": {
"pino": "6.11.2",
"pino-logflare": "0.3.8"
}

**Comment by timakhalaya** [comment]
additional info , this is started to happen after i moved next.js application to webpack version 5

**Comment by timakhalaya** [comment]
You should check on the server side only when implementing the logger ...
Checking that window is undefined and then implementing the logic

**Comment by jacklimwenjie** [comment]
I have the same issue after upgrade Next.js to version 11

**Comment by timakhalaya** [comment]
```
if (typeof window === 'undefined') {
    /**
     *  Loaded in try block we wont receive the error about the writableStream being not loaded
     */
    // create stream
    const stream = createConsoleWriteStream({ apiKey, sourceToken })
    // create pino-logflare console stream for serverless functions and send function for browser logs
    const { send } = logflarePinoVercel({ apiKey, sourceToken })
    pinoLoggerLoaded = pino(
        {
            browser: {
                transmit: {
                    level: 'info',
                    send
                }
            },
            level: 'info',
            base: {
                siteEnvironment: getVercelEnv(),
                application: getApplicationName()
            }
        },
        stream
    )
}
```

that will solve it for u

**Comment by anguskeatinge** [comment]
If you've run into this after moving to next v11, the easiest solution is to drop back to webpack 4 by adding the option `webpack5: false,` in `next.config.js`

**Comment by timakhalaya** [comment]
though, u might still need w5 for yarn2 for example...

**Comment by anguskeatinge** [comment]
Also a rookie error on my part not realising this lib isn't meant for client side logging...
Thanks for your help @timakhalaya !!!

**Comment by chasers** [comment]
Thanks for your patience all ... finally able to devote some time to this today and tomorrow. 

@anguskeatinge it actually does handle client side logging also. If you don't need client side logging you can just use straight pinojs, in which case your client side logs will just go to the console.

**Comment by chasers** [comment]
I was able to replicate this in a test project, and the pull request from @yhjor fixes it for me. Please try [v0.3.9](https://github.com/Logflare/pino-logflare/releases/tag/v0.3.9) and let me know.

**Comment by anguskeatinge** [comment]
Works a charm
