### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by yoeran** [Logflare/pino-logflare#3]
Since yesterday I'm getting an error when trying to install pino-logflare from npm.

This is what I get after running `npm i pino-logflare`. It used to work just fine, encountering this on my local setup as well as in CI/CD pipeline.

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/<path-to-project>/node_modules/pino-logflare/src/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/<path-to-project>/node_modules/pino-logflare/src/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by yoeran** [comment]
I guess it has to do with this line in package.json: https://github.com/Logflare/pino-logflare/blob/e6a5c1b8a6e9ad8b8f575a17ad922011384ecd28/package.json#L14

It still references `src/cli.js` instead of `src/cli.ts` or `dist/cli.js`. I started to make a pull request, but I have too little knowledge on the inners of npm packages, so I don't know how to test it.

**Comment by chasers** [comment]
Got it ... will have a fix pushed here shortly.

**Comment by chasers** [comment]
@yoeran @jpwilliams 0.3.2 is published. Thanks!!
