### ISSUE TITLE
logger ignores arguments that are not string or object (i.e. numbers)

### ISSUE THREAD

**Issue by patelnav** [Logflare/pino-logflare#30]
If you log the following:
`logger.info("Hello world", 2021)`

The 2021 will get dropped entirely as doesn't pass [isObject nor isString](https://github.com/Logflare/pino-logflare/blob/f80d45e0643ff8f7dd20b1c2249f7ca48a7846e4/src/utils.ts#L49)

**Comment by chasers** [comment]
Yeah that function is supposed to really be like `logger.info(metadata, message)` where `metadata` is an object and `message` is a string. The `message` is what will show up in your log stream in your Logflare account.

You can see some more examples here:

https://github.com/Logflare/next-pino-logflare-logging-example/tree/main/pages/api

**Comment by patelnav** [comment]
ah, my assumption was it would try to match the [console.log](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) behaviour.
