### ISSUE TITLE
Would you consider a Roarr transport?

### ISSUE THREAD

**Issue by gajus** [Logflare/pino-logflare#39]
[Roarr](https://github.com/gajus/roarr) is another logging framework that is downloaded over 1M / month.

https://www.npmjs.com/package/roarr

Would be happy to contribute.

**Comment by chasers** [comment]
@gajus we'd love some help getting this done!  If you can do it we'd definitely include it.  Let me know if you need any help with anything.

**Comment by Ziinc** [comment]
Closing for now. Feedback has been noted internally [here](https://www.notion.so/supabase/Roarr-log-transport-04563a90327c4d0189c7101339d0e981), if anyone wants to contribute an implementation we would be happy to review.
