### ISSUE TITLE
Cannot use the filter ??

### ISSUE THREAD

**Issue by nukecrypto** [Logflare/pino-logflare#40]
I'm no following here. I dont know if this is a logflare issue, pino issue, or something else.... 

![image](https://user-images.githubusercontent.com/91539256/145652972-98bb789f-d73e-4b8b-b6b4-072d5508291e.png)

**Comment by chasers** [comment]
Thanks for reporting.  Yeah this is a bug.  Should be resolved next week.

**Comment by chasers** [comment]
@nukecrypto this is fixed!!
