### ISSUE TITLE
Document "endpoint" and "fromBrowser" options

### ISSUE THREAD

**Issue by HoverBaum** [Logflare/pino-logflare#5]
It would be great to see more documentation on the "endpoint" and "fromBrowser" options that `createWriteStream` and `logflarePinoVercel` require.

Trying to integrate pino based logging to Logflare in my TS based serverless Vercel backend. Only providing `apiKey` and `sourceToken` doesn't seem to do the trick just yet and my compiler prompted me to look into the above mentioned options. Digging through the code and the transport code it's still a mystery to me what I should set those to.

Would be awesome to see more docs and example for use cases 😁

**Comment by chasers** [comment]
Will do. We have a guide to be published pending Vercels approval. 

Take a look at this: https://github.com/Logflare/pino-logflare-nextjs-vercel-example/blob/main/logger/logger.js

That all works as it should. Maybe there is something I missed to mention.

**Comment by chasers** [comment]
What exactly are you seeing?

**Comment by HoverBaum** [comment]
Inspired from the docs my current code is:

```
import pino from 'pino'
import { logflarePinoVercel } from 'pino-logflare'

// create pino-logflare console stream for serverless functions and send function for browser logs
// @ts-ignore
const { stream, send } = logflarePinoVercel({
  apiKey: 'xx-x-xxxxxxx',
  sourceToken: 'ecb6277f-b0fc-44c9-xxxx-xxxxxxxxxxxx',
})

// create pino loggger
const logger = pino(
  {
    browser: {
      transmit: {
        level: 'info',
        send: send,
      },
    },
    level: 'debug',
    base: {
      env: process.env.ENV || 'ENV not set',
      revision: process.env.VERCEL_GITHUB_COMMIT_SHA,
    },
  },
  stream
)

export default logger

```

Now when I use the logger in my function I do see structured outputs in the function tab on Vercel but nothing seems to reach Logflare.

**Comment by chasers** [comment]
Did you setup the [Logflare + Vercel integration](https://vercel.com/integrations/logflare)?  That will tell Vercel's log drains to send events to Logflare.

Currently the only JS lib yes, but you can just send over a POST request. When you're in a Logflare source click `send more logs` for examples.

[This branch](https://github.com/Logflare/pino-logflare-nextjs-vercel-example/blob/with-pino-logflare-3/logger/logger.js) is an example of going straight to Logflare (not via Vercel's logs) but there are some advantages to using Vercel's system as they put the logs nested in the request context so you can url and response times automatically.

**Comment by HoverBaum** [comment]
Did setup the integration. I am seeing access logs in Logflare like a request was made to xyz.

Definitely am seeing the advantage in getting the Vercel context and would love to get that to work. 

I will try the direct logging and see if that gives me some logs.

**Comment by HoverBaum** [comment]
Got the direct connection example to work after switching my logging from `logger.debug` to `logger.info` in my function code.

Sill can't get `logflarePinoVercel` to work though 🤔

Noticing that while the integration was working I didn't see the structured Pino output in the Vercel "Functions" tab. But with the not working vercel-pino way I see the structured Pino log there.

Is there a way to debug this further?

**Comment by chasers** [comment]
> Noticing that while the integration was working I didn't see the structured Pino output in the Vercel "Functions" tab. But with the not working vercel-pino way I see the structured Pino log there.

Not 100 percent sure what you’re saying here. 

With ‘logflarePinoVercel‘ you should see the structured log on the Vercel lambda log page. And it should just get routed to Logflare if you have the integration setup. 

To send logs to the Vercel log drain it just puts them in stdout. You could not even use pino or pino-logflare and just do a console.log(“whatever”) and with the Logflare Vercel integration that should come through to Logflare. Maybe let’s get that working first and go from there.

**Comment by HoverBaum** [comment]
Ahh that would have been my expectation from the get go, would have been awesome to get that going and become agnostic of which logging library to use.

I followed the Vercel guide at: https://logflare.app/guides/vercel-setup
And am now seeing logs from my builds and for every request to static hosting as well as my function.

```
Thu Jul 9 2020 22:36:50 static | 200 | my-app.vercel.app | /img/login.png | 157.245.2.105 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Safari/537.36 Chrome-Lighthouse metadata
Thu Jul 9 2020 22:37:09 build | Uploading build cache [245.37 MB]... metadata
Thu Jul 9 2020 22:37:13 build | Build cache uploaded: 3555.336ms metadata
Thu Jul 9 2020 22:37:13 build | Done with "package.json" metadata
Thu Jul 9 2020 22:45:46 lambda | 200 | my-app.vercel.app | /api/insights?query=param | 188.108.180.203 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 metadata
```

But while I see `My Log output` on my Functions tab in Vercel I do not see it anywhere on Logflare.

**Comment by chasers** [comment]
Okay great! Click on the metadata link you should see the parsed lambda message in the `parsedLambdaMessage` key!! That is also where your structured data will be when you start sending over that.  I'll auto parse that into a JSON object for you so you can query it like `m.parsedLambdaMessage.lines.data.your_field:~"will match this text"`

**Comment by HoverBaum** [comment]
Awesome 😊

I see things coming through, maybe just missed them before 🙈

Now, 

1. totally unrelated to the original headline. The parsing seems to fail when I use both structured data logs from Pino and simple console.logs in the same function. At least that resulted in `"parse_status": "failed"` in my case.
Using either two Pino logs or two console.logs works fine.

2. I am still wondering about the "endpoint" and "fromBrowser" flags that my TS compiler wants me to set for `logflarePinoVercel`.

Thanks so much for the help. I hope this isn't turning into a personal help request but will be something useful for future users as well 😁

**Comment by chasers** [comment]
> totally unrelated to the original headline. The parsing seems to fail when I use both structured data logs from Pino and simple console.logs in the same function. At least that resulted in "parse_status": "failed" in my case.
Using either two Pino logs or two console.logs works fine.

Yep, use one or the other. Theoretically, we can support both at the same time but the parser doesn't handle that currently.

> I am still wondering about the "endpoint" and "fromBrowser" flags that my TS compiler wants me to set for logflarePinoVercel.

Can you paste the output here and/or give me a project to clone that replicates this? Those are from `logflare-transport-core-js` ... I will have to dig more.

> I hope this isn't turning into a personal help request

Totally cool ... good for Google. Closing for now!

**Comment by HoverBaum** [comment]
TS output goes like this:

```
Argument of type '{ apiKey: string; sourceToken: string; }' is not assignable to parameter of type 'LogflareUserOptionsI'.
  Type '{ apiKey: string; sourceToken: string; }' is missing the following properties from type 'LogflareUserOptionsI': endpoint, fromBrowser
```

**Comment by davidknezic** [comment]
Hi @HoverBaum, was just surprised by the same type error. The docs imply only `apiKey` and `sourceToken` must be provided, but the TypeScript definitions of `logflare-transport-core` require two more fields. Had a look at the implementation and this is how I run the transport now: 

```js
const stream = createWriteStream({
  apiKey: process.env.LOGFLARE_API_KEY,
  sourceToken: process.env.LOGFLARE_SOURCE_TOKEN,
  endpoint: '', // can be any string really, only if it's set to 'typecasting' the alternative '/logs/typecasts' endpoint is instead of '/logs'
  fromBrowser: false, // doesn't matter if true or false as much as I can see
});
```

**Comment by chasers** [comment]
Okay we will fix.

**Comment by HoverBaum** [comment]
@davidknezic great find 👍 

@chasers personally I would love if this library would abstract the need for those two options away so that we can just pass apiKey and sourceToken.

**Comment by chasers** [comment]
Yeah those shouldn't be required!  Planning for some typecasting because of javascript number types. 

This should be fixed > https://github.com/Logflare/pino-logflare/releases/tag/v0.3.4
