### ISSUE TITLE
Remove use of public facing typescript any types (e.g., 'stream')

### ISSUE THREAD

**Issue by tettoffensive** [Logflare/pino-logflare#54]
I'm not sure if it's appropriate to change `any` for the `stream` for `logflarePinoVercel` to possibly `pino.DestinationStream` or something else? For projects like mine, it requires adding `/* eslint-disable @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-assignment */`

v0.3.12
```ts
declare const logflarePinoVercel: (options: LogflareUserOptionsI) => {
    stream: any;
    send: (level: Level, logEvent: LogEvent) => void;
};
```

**Comment by chasers** [comment]
Thanks for this, I'll tee it up to take a look at next week.

**Comment by tettoffensive** [comment]
@chasers Any thoughts on this?

**Comment by Ziinc** [comment]
This issue should be outdated as `logflarePinoVercel` is no longer typed explicitly with an `any`
https://github.com/Logflare/pino-logflare/blob/4d0de2d44ee36136d22979c8697008bc5d11c455/src/index.ts#L35C7-L35C25

Please reopen if the issue persists.
