### ISSUE TITLE
Getting Error: Logflare API request failed: [object Object] in my Next JS app.Using pino logflare latest

### ISSUE THREAD

**Issue by anantsjb** [Logflare/pino-logflare#58]
Hi, Facing issue while logging
<img width="853" alt="Screen Shot 2022-08-22 at 11 16 56 PM" src="https://user-images.githubusercontent.com/33336407/186068800-3d334988-427c-4290-8e90-cec1f834a3a3.png">

**Comment by Ziinc** [comment]
@anantsjb could you show how you're making the requests?

So that I can try to replicate.

**Comment by anantsjb** [comment]
> 

yes thanks @Ziinc for looking into it 
!
![Screen Shot 2022-08-23 at 11 16 14 AM](https://user-images.githubusercontent.com/33336407/186209621-91e48bc8-791f-4f74-b283-eacfdb7fbd1d.png)
[Screen Shot 2022-08-23 at 11 15 31 AM](https://user-images.githubusercontent.com/33336407/186209597-46fcb687-4f66-4532-855f-cd4e1e5edf31.png)

**Comment by Ziinc** [comment]
Could you adjust the `logger.error()` call to instead call as per the api docs [here](https://github.com/Logflare/pino-logflare/blob/master/docs/API.md)

```
logger.error("something") 
logger.error({test: "testing" }, " a message") 
```
According to the pino docs, the first positon of the of the first two args is an an optional object.

**Comment by Ziinc** [comment]
closing for now.
