### ISSUE TITLE
Append custom key, value in metadata

### ISSUE THREAD

**Issue by rahilwazir** [Logflare/pino-logflare#7]
How can I transmit custom key:values to Logflare metdata object?

I tried many instances of logger

```js
logger.info({metadata: "asdasd"});
```

```js
logger.info("some text", {metadata: "asdasd"});
```

None worked, please let me know what is the easiet way to push data to existing (parent) logger.

**Comment by chasers** [comment]
Can you give me some more info? You're using the latest version?  Are you getting an error or anything?

**Comment by rahilwazir** [comment]
@chasers Sure,

Extracted from `package.json`:

```json
"pino": "^6.4.1",
"pino-logflare": "^0.3.4",
```

There are no errors, the logging is actually working fine. If you see the screenshot below, I want to push more verbose data under `metadata`, instead of large stringify objects inline.

![image](https://user-images.githubusercontent.com/1818941/88458885-7c190c80-ceaa-11ea-9a10-f136dd0f93f5.png)

If I create a child logger

```js
const logger = pinoLogger.child({ module: "App", inspect: 0 });
```

Those parameters is then placed inside the `metadata` (see screenshot), but I want the ability to push that data each time when I use any level of logs `.info(..)`, `.error(..)` with the `logger` instance.

```js
logger.info('Inline log message', {a: 1, b: 2} ) // the second parameter should display in metadata or if any other method?
```

Does it make sense? Thanks

**Comment by chasers** [comment]
Ah yep!  Try this...

```
  const child = logger.child({ a_field: 'property' })

  child.info({ b_field: 'another property' }, 'hello world')
```

<img width="659" alt="Screen Shot 2020-07-25 at 10 52 52 AM" src="https://user-images.githubusercontent.com/1019814/88463092-0f2f5380-ce65-11ea-94f9-cd5f583628f2.png">

Assuming you're instantiating `logger` like so: https://github.com/Logflare/pino-logflare/blob/master/docs/API.md

**Comment by rahilwazir** [comment]
Well I'm not sure why is it not working in my case. Do note I'm using the pino-logflare on browser.

Here's is my full code (omitted the api keys).

```js
import pino from "pino";
import { createPinoBrowserSend, createWriteStream } from "pino-logflare";

// create pino-logflare stream
const stream = createWriteStream({
  apiKey: "...",
  sourceToken: "..."
});

// create pino-logflare browser stream
const send = createPinoBrowserSend({
  apiKey: "...",
  sourceToken: "..."
});

// create pino loggger
const logger = pino(
  {
    browser: {
      transmit: {
        send: send
      }
    }
  },
  stream
);

const childLogger = logger.child({ a_field: 'property' });
childLogger.info({msg: "asdasd"}, "hello world");
```

![image](https://user-images.githubusercontent.com/1818941/88477494-d6bd7180-cf59-11ea-8ac5-84d88f2c1ae8.png)

The first parameter (object) is always converted as string, and added as inline `[object Object]` to the logs. The `msg` key never gets into the `metadata`.

**Comment by chasers** [comment]
Oh, okay I see. Yeah the behavior is different on the client vs the server.  Server side it works as expected, client side does not.  Okay this is a bug, sorry for the confusion.  We'll fix.

**Comment by rahilwazir** [comment]
Alright, thanks.

As of now, I'm overriding the `send` function to mitigate this. Found out the property `bindings` in `logEvent` holds the metadata values.
So I check the type of input in the `messages` property and if it is an object, push it to the `bindings` array and remove it from the `messages` property.

So far it's working great, and since objects are inspectable in browser console, I didn't have to do anything in the `write` method.

```js
...
browser: {
  transmit: {
    send(level, logEvent) {
      logEvent.bindings = [];

      for (const [index, message] of Object.entries(logEvent.messages)) {
        if (typeof message === "object") {
          logEvent.bindings.push(message);
          logEvent.messages.splice(index, 1);
        }
      }
      send(level, logEvent);
    }
  }
}
...
```

**Comment by chasers** [comment]
Nice! Glad you figured out a workaround.

Can you please check out [the latest release](https://github.com/Logflare/pino-logflare/releases/tag/v0.3.5) and let me know if it works for you?  I think we got it!

**Comment by rahilwazir** [comment]
That fixes it, thank you
